version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # depends_on:
    #   - backend
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=rent_agency

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80