# Utiliza la imagen base de Node.js
FROM node:20-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de configuración y de dependencias
COPY package*.json .

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación al directorio de trabajo
COPY . .

# Puerto en el que se ejecutará la aplicación (si es necesario)
EXPOSE 5173

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]